export default {
    전사:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/warrior.png",
    워로드:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_warlord.png",
    디스트로이어:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_destroyer.png",
    버서커:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_berserker.png",
    홀리나이트:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_holyknight.png",
    "무도가 (남)":"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/fightermale.png",
    스트라이커:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_striker.png",
    무도가:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/fighter.png",
    배틀마스터:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_battlemaster.png",
    인파이터:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_infighter.png",
    기공사:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_soulmaster.png",
    창술사:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_lancemaster.png",
    "헌터 (남)":"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/hunter.png",
    데빌헌터:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_devilhunter.png",
    블래스터:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_blaster.png",
    호크아이:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_hawkeye.png",
    스카우터:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_scouter.png",
    "헌터 (여)":"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/hunterfemale.png",
    건슬링어:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_gunslinger.png",
    마법사:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/magician.png",
    바드:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_bard.png",
    서머너:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_summoner.png",
    아르카나:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_arcana.png",
    소서리스:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_sorceress.png",
    암살자:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/assassin.png",
    블레이드:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_blade.png",
    데모닉:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_demonic.png",
    리퍼:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_reaper.png",
    스페셜리스트:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/specialist.png",
    도화가:"https://cdn-lostark.game.onstove.com/2018/obt/assets/images/common/thumb/emblem_artist.png"
}